server:
  port: 8080
  error:
    include-message: always
    whitelabel:
      enabled: false
    path: /error
spring:
  application:
    name: "boilerplate-server"
  profiles:
    active: "default"
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/smosky
    username: loctran
    password: Loc123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
      format-sql: true
    show-sql: false
  config:
    import: "optional:configserver:http://localhost:8070"
    logging.level:
      org.springframework.security: TRACE
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"